### ISSUE TITLE
test FPS of rendering

### ISSUE THREAD

**Issue by JiatengLiu** [skhu101/GauHuman#15]
I wanted to test the render speed (FPS) of the model, but the output of the code (~300) was inconsistent with the results in the paper (100+). I made the following changes to the `dataset_reader.py`(558-562), but the result is still incorrect. How can I solve it?
```    elif split == 'test':
        pose_start = 0
        # pose_interval = 30
        pose_interval = 1
        pose_num = 17
```

**Comment by skhu101** [comment]
Hi, the rendering FPS depends on the GPU version and its working state. It is possible to reach 300 FPS as the code structure is optimized before it is released.

**Comment by GloryyrolG** [comment]
Would you mind giving some insights/tips on how to boost FPS further or sharing some snippets? Great thx & best,

**Comment by skhu101** [comment]
Hi, maybe one possible solution is to further optimize the number of 3D Gaussians. You can also try improving the parallel mechanism as the GPU memory is not fully used.
