### ISSUE TITLE
ValueError: cannot reshape array of size 620100 into shape (6890,3)

### ISSUE THREAD

**Issue by JasonTian1091** [skhu101/GauHuman#17]
When I run `train_zju_mocap_refine.sh`, an error occurs: The issue seems to arise when attempting to reshape the array, as its size does not match the expected shape of (6890, 3).
![image](https://github.com/skhu101/GauHuman/assets/26952474/9ccccd08-7361-46ab-ad4a-8685b93225d1)

![image](https://github.com/skhu101/GauHuman/assets/26952474/ad08d488-ab37-4208-9923-6dc771e9d439)
If I could receive your assistance, I would be extremely grateful.

**Comment by skhu101** [comment]
Hi, it is quite strange. Could you show me the dimension of parameters in big_pose_smpl_param and the dimension of shapedirs and v_template in smpl_numpy.py?

**Comment by JasonTian1091** [comment]
![image](https://github.com/skhu101/GauHuman/assets/26952474/4d72ed18-fdf1-40ec-847e-3c87cf6324ca)
but the explanation is different.
![image](https://github.com/skhu101/GauHuman/assets/26952474/0a2565cc-a527-44d6-8a56-98ebceaebb0d)
i'm confused.

**Comment by Malcclon** [comment]
Hi,I also meet the same problem,I tried two versions from https://smpl.is.tue.mpg.de/download.php,but it seems that the version v1.0.0 lacks the neutral model, and I met the same problem above when I used the neutral smpl from v1.1.0 version,would you mind telling me how did you solve the problem,thanks a lot !

**Comment by RxChi1d** [comment]
> Hi,I also meet the same problem,I tried two versions from https://smpl.is.tue.mpg.de/download.php,but it seems that the version v1.0.0 lacks the neutral model, and I met the same problem above when I used the neutral smpl from v1.1.0 version,would you mind telling me how did you solve the problem,thanks a lot !

I have the sample question.
Can anyone help?

Thanks a lot!

**Comment by RxChi1d** [comment]
> Hi,I also meet the same problem,I tried two versions from https://smpl.is.tue.mpg.de/download.php,but it seems that the version v1.0.0 lacks the neutral model, and I met the same problem above when I used the neutral smpl from v1.1.0 version,would you mind telling me how did you solve the problem,thanks a lot !

I have the same question in the begining.
And I try the SMLP model which requires in [HumanNeRF](https://github.com/chungyiweng/humannerf), it works.
You can test it.

Have a nice day.

**Comment by imabackstabber** [comment]
> > Hi,I also meet the same problem,I tried two versions from https://smpl.is.tue.mpg.de/download.php,but it seems that the version v1.0.0 lacks the neutral model, and I met the same problem above when I used the neutral smpl from v1.1.0 version,would you mind telling me how did you solve the problem,thanks a lot !
> 
> I have the same question in the begining. And I try the SMLP model which requires in [HumanNeRF](https://github.com/chungyiweng/humannerf), it works. You can test it.
> 
> Have a nice day.

This works for me. It turns out you need to get to [SMPLify Page](https://smplify.is.tue.mpg.de/download.php) to download. A update on README.md is needed.

**Comment by skhu101** [comment]
Hi, thanks for your information. Have updated the README.md.
