### ISSUE TITLE
Why the code can be run directly in vscode, but a RuntimeError occurs when debugging

### ISSUE THREAD

**Issue by sycamore27** [skhu101/GauHuman#19]
Why the code can be run directly in vscode, but a RuntimeError occurs when debugging: 

发生异常: RuntimeError
Error building extension 'knn': [1/3] /usr/local/cuda-11.8:/usr/local/cuda-11.8/bin/nvcc  -DTORCH_EXTENSION_NAME=knn -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/TH -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.8:/usr/local/cuda-11.8/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -std=c++17 -c /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/knn_cuda/csrc/cuda/knn.cu -o knn.cuda.o 
FAILED: knn.cuda.o 
/usr/local/cuda-11.8:/usr/local/cuda-11.8/bin/nvcc  -DTORCH_EXTENSION_NAME=knn -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/TH -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.8:/usr/local/cuda-11.8/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -std=c++17 -c /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/knn_cuda/csrc/cuda/knn.cu -o knn.cuda.o 
/bin/sh: 1: /usr/local/cuda-11.8:/usr/local/cuda-11.8/bin/nvcc: not found
[2/3] c++ -MMD -MF knn.o.d -DTORCH_EXTENSION_NAME=knn -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/TH -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.8:/usr/local/cuda-11.8/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O2 -c /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/knn_cuda/csrc/cuda/knn.cpp -o knn.o 
FAILED: knn.o 
c++ -MMD -MF knn.o.d -DTORCH_EXTENSION_NAME=knn -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/TH -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.8:/usr/local/cuda-11.8/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O2 -c /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/knn_cuda/csrc/cuda/knn.cpp -o knn.o 
In file included from /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/knn_cuda/csrc/cuda/knn.cpp:3:
/home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: No such file or directory
    5 | #include <cuda_runtime_api.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

  File "/home/qinzhen/GauHuman/scene/gaussian_model.py", line 23, in <module>
    from knn_cuda import KNN
  File "/home/qinzhen/GauHuman/scene/dataset_readers.py", line 28, in <module>
    from scene.gaussian_model import BasicPointCloud
  File "/home/qinzhen/GauHuman/scene/__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "/home/qinzhen/GauHuman/gaussian_renderer/__init__.py", line 15, in <module>
    from scene.gaussian_model import GaussianModel
  File "/home/qinzhen/GauHuman/train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
RuntimeError: Error building extension 'knn': [1/3] /usr/local/cuda-11.8:/usr/local/cuda-11.8/bin/nvcc  -DTORCH_EXTENSION_NAME=knn -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/TH -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.8:/usr/local/cuda-11.8/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -std=c++17 -c /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/knn_cuda/csrc/cuda/knn.cu -o knn.cuda.o 
FAILED: knn.cuda.o 
/usr/local/cuda-11.8:/usr/local/cuda-11.8/bin/nvcc  -DTORCH_EXTENSION_NAME=knn -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/TH -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.8:/usr/local/cuda-11.8/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -std=c++17 -c /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/knn_cuda/csrc/cuda/knn.cu -o knn.cuda.o 
/bin/sh: 1: /usr/local/cuda-11.8:/usr/local/cuda-11.8/bin/nvcc: not found
[2/3] c++ -MMD -MF knn.o.d -DTORCH_EXTENSION_NAME=knn -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/TH -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.8:/usr/local/cuda-11.8/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O2 -c /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/knn_cuda/csrc/cuda/knn.cpp -o knn.o 
FAILED: knn.o 
c++ -MMD -MF knn.o.d -DTORCH_EXTENSION_NAME=knn -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/TH -isystem /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-11.8:/usr/local/cuda-11.8/include -isystem /home/qinzhen/anaconda3/envs/gauhuman/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O2 -c /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/knn_cuda/csrc/cuda/knn.cpp -o knn.o 
In file included from /home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/knn_cuda/csrc/cuda/knn.cpp:3:
/home/qinzhen/anaconda3/envs/gauhuman/lib/python3.8/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: No such file or directory
    5 | #include <cuda_runtime_api.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

**Comment by skhu101** [comment]
Hi, maybe you can try installing pytorch3d and using the KNN in pytorch3d.
