### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Tiandishihua** [skhu101/GauHuman#2]
How do I make my own video dataset?

**Comment by skhu101** [comment]
Hi, I think you should prepare the following things. 1). Estimate the SMPL and camera parameters using the single-view-based SMPL estimation methods or video-based SMPL estimation methods, 2). Get the mask of human performers in the video. Then you can use our method to reconstruct 3D humans.

**Comment by Ramseyous0109** [comment]
@skhu101 Hi, thanks for this wonderful work. I'm also interested in running GauHuman on customized datasets. I tried methods like [mmhuman3d](https://github.com/open-mmlab/mmhuman3d/) to generate SMPL parameters. However, it seems that the parameters format are quite different from those in ZJU-Mocap and MonoCap dataset(eg. size of poses). I wonder if you could give some advice on how to modify the dataset loaders or transfer the parameter format.  Thanks!

**Comment by skhu101** [comment]
Hi, could you show the specific difference between these two formats of SMPL parameters?

**Comment by Ramseyous0109** [comment]
Thanks for your reply. Definitely, here are the parameter of these two formats: 

For the output of the mmhuman3d model, the parameters are:

- `'body_pose'`: which seems to correspond to the param `'poses'`   in the SMPL model in the datasets. However, the shape is `(1,23)`  in mmhuman3d output compared to `(1,72)` in the datasets (for one human).
- `'global_orient'` which seems to correspond to the params `'Rh'` indicating the rotation of the SMPL model in the datasets.
- `'betas'` which seems to correspond to the params `'shapes'` in the SMPL model with the same shape of `'(1,10)'`
- No params corresponding to the `'Th'` in the SMPL model in the datasets.

I think there are two main differences: 

1. Size of params of the body pose.
2. It seems to me that in the datasets, the translation vector of the model is extracted from the body poses, but this process isn't done by mmhuman3d.

I'll try to modify the dataloaders myself and look forward to your further reply.

**Comment by caizhongang** [comment]
@Ramseyous0109 Hi, how you run MMHuman3D to obtain the parameters?

**Comment by Ramseyous0109** [comment]
@caizhongang Thanks for your reply. I just ran the [demo/estimate_smpl.py](https://github.com/open-mmlab/mmhuman3d/blob/main/demo/estimate_smpl.py).

**Comment by caizhongang** [comment]
> @caizhongang Thanks for your reply. I just ran the [demo/estimate_smpl.py](https://github.com/open-mmlab/mmhuman3d/blob/main/demo/estimate_smpl.py).

Hi @Ramseyous0109 , the script should have output `body_pose` in shape (-1, 23, 3) as in this [line](https://github.com/open-mmlab/mmhuman3d/blob/main/demo/estimate_smpl.py#L256). Can you try the following snippet:
```
import numpy as np
content = np.load('output.npz', allow_pickle=True)
body_pose = content['smpl'].item()['body_pose']
print(body_pose.shape)
```

**Comment by Ramseyous0109** [comment]
@caizhongang  Sorry for making this shape wrong. The shape of `body_pose` is actually `(1,23,3)`.
Then is there a way to transfer it into the shape needed by GauHuman?

**Comment by caizhongang** [comment]
> @caizhongang Sorry for making this shape wrong. The shape of `body_pose` is actually `(1,23,3)`. Then is there a way to transfer it into the shape needed by GauHuman?

@Ramseyous0109 , since the target shape is `(1,72)`, my best guess is to reshape `body_pose` to `(1, 69)` and concatenate global orient (shape is `(1, 3)`): `np.concatenate([global_orient, body_shape]), axis=-1)`.

**Comment by Ramseyous0109** [comment]
@caizhongang Thanks so much. I'll try this way.

**Comment by JiatengLiu** [comment]
@Ramseyous0109 hello! Did you make the data set correctly? If so, can I expose your script? Thank you so much:>

**Comment by Ramseyous0109** [comment]
@JiatengLiu Hi, I think you can just follow the steps above to match the parameter keys to generate scripts for customized dataset.

**Comment by JiatengLiu** [comment]
yes, I have finished it.

--------------原始邮件--------------
发件人："Ramseyous0109 ***@***.***&gt;;
发送时间：2024年5月6日(星期一) 晚上6:31
收件人："skhu101/GauHuman" ***@***.***&gt;;
抄送："Jett ***@***.***&gt;;"Mention ***@***.***&gt;;
主题：Re: [skhu101/GauHuman] dataset (Issue #2)
----------------------------------

 

 
@JiatengLiu Hi, I think you can just follow the steps above to match the parameter keys to generate scripts for customized dataset.

**Comment by NagabhushanSN24** [comment]
> @skhu101 Thanks for your reply. Definitely, here are the parameter of these two formats:
> 
> For the output of the mmhuman3d model, the parameters are:
> 
> * `'body_pose'`: which seems to correspond to the param `'poses'`   in the SMPL model in the datasets. However, the shape is `(1,23)`  in mmhuman3d output compared to `(1,72)` in the datasets (for one human).
> * `'global_orient'` which seems to correspond to the params `'Rh'` indicating the rotation of the SMPL model in the datasets.
> * `'betas'` which seems to correspond to the params `'shapes'` in the SMPL model with the same shape of `'(1,10)'`
> * No params corresponding to the `'Th'` in the SMPL model in the datasets.
> 
> I think there are two main differences:
> 
> 1. Size of params of the body pose.
> 2. It seems to me that in the datasets, the translation vector of the model is extracted from the body poses, but this process isn't done by mmhuman3d.
> 
> I'll try to modify the dataloaders myself and look forward to your further reply.

By any chance, does `Rh` correspond to translation vector? Then body-pose + global-orient = 72 params

**Comment by skhu101** [comment]
Yes, your understanding is correct.

**Comment by Daydreamer-f** [comment]
@Ramseyous0109 @JiatengLiu  I have used mmhuman3d to generate SMPL parameters and have modified some variables according to the previous responses. However, I am still experiencing some issues with matching. Could I take a look at how you modified the `def readCamerasZJUMoCapRefine` function in `dataset_reader.py` ? 

Specifically, I am unsure how to match the results from mmhuman3d with `annots.npy`. I am also confused about what the `Th` variable in smpl_params should correspond to and what the `xyz` in smpl_vertices should correspond to. I would appreciate your guidance on these points.

Thank you!

**Comment by JiatengLiu** [comment]
could you give me a e-mail for contact?

**Comment by Daydreamer-f** [comment]
@JiatengLiu 
Sure, here's my email: ysfang0306@gmail.com
Thanks a lot!

**Comment by Daydreamer-f** [comment]
> could you give me a e-mail for contact?

@JiatengLiu Hi, I haven't received your email yet. Could you please provide me with your email address for contact?

**Comment by JiatengLiu** [comment]
sended

**Comment by gt732** [comment]
@JiatengLiu can you also email me the details thanks!

geuryt@yahoo.com

**Comment by JiatengLiu** [comment]
Just follow [instantNVR](https://github.com/zju3dv/instant-nvr/blob/master/docs/preprocess.md). I found out later that this repo is adaptive.
