### ISSUE TITLE
How to calculate sdf for world_src_pts

### ISSUE THREAD

**Issue by yejr0229** [skhu101/GauHuman#20]
Hi,Id like to calculate signed distances for world_src_pts in gaussian_model.py,so I can know whether this point is inside body or not.Could you tell me how to achieve this roughly?

**Comment by skhu101** [comment]
Hi, thanks for your interest in our work. One possible way is to find the nearest face in the SMPL vertices and then calculate the signed distances to this face. If you hope to involve the SDF concept in the modelling framework, maybe you can refer to 3DGSR: Implicit Surface Reconstruction with 3D Gaussian Splatting (https://arxiv.org/pdf/2404.00409.pdf).
