### ISSUE TITLE
CUDA OUT OF MEMORY

### ISSUE THREAD

**Issue by ZhaoLizz** [skhu101/GauHuman#23]
Hi! 
I encountered an issue while running the training code using the provided train_zju_mocap_refine.sh script on a single Nvidia RTX 4090 GPU. It appears that the rasterizer is demanding 72 GB GPU memory.

I'm reaching out to inquire if any specific parameters within the script or configuration can be adjusted to reduce the GPU memory requirements to a more manageable level. 

Thank you for your assistance.
![image](https://github.com/skhu101/GauHuman/assets/29300861/1319cbc0-9541-4eae-ba92-a2a9e549dcf6)

**Comment by skhu101** [comment]
Hi, I did not encounter this problem during my training. Do you check the dimensions of the parameters for rasterizer function?

**Comment by ZhaoLizz** [comment]
Currently, I'm working on other GS-based Avatar projects. I have encountered that if the init GS scale is too large, it leads to CUDA out of memory. I'm not sure whether GauHuman met the same reason, but for anyone who encounters similar error,  reducing scale for the first few epochs worth a try.
