### ISSUE TITLE
not enough values to unpack (expected 4, got 2)

### ISSUE THREAD

**Issue by XvHaidong** [skhu101/GauHuman#25]
Hello there,
Could you please tell me what the problem is?
I really follow your script, but When I run  train_zju.sh, I got something wrong:  

________________________________________________________________________________
_________________________________________________________________________

/data/xhd/envs/gaussian/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /data/xhd/envs/gaussian/lib/python3.7/site-packages/lpips/weights/v0.1/vgg.pth
Optimizing 
Output folder: ./output/zju_mocap_refine/386_100_pose_correction_lbs_offset_split_clone_merge_prune [05/04 15:41:47]
Tensorboard not available: not logging progress [05/04 15:41:47]
Found annots.json file, assuming ZJU_MoCap_refine data set! [05/04 15:41:47]
Reading Training Transforms [05/04 15:41:47]
Reading Test Transforms [05/04 15:41:54]
Loading Training Cameras [05/04 15:42:20]
Loading Test Cameras [05/04 15:42:24]
Number of points at initialisation :  6890 [05/04 15:42:27]
Training progress:   0%|                                                                                    | 0/1200 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 301, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 104, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background)
  File "/data/xhd/3D/GauHuman/gaussian_renderer/__init__.py", line 119, in render
    cov3D_precomp = cov3D_precomp)
ValueError: not enough values to unpack (expected 4, got 2)
Training progress:   0%|

**Comment by XvHaidong** [comment]
My fault, sorry

**Comment by AndingDrLin** [comment]
Hi! I have the same problem with you. Can you tell me how you tackled this problem?

**Comment by vvsherryvv** [comment]
> Hi! I have the same problem with you. Can you tell me how you tackled this problem?

hi！are you solve this problem？i have the same problem.

**Comment by vvsherryvv** [comment]
> My fault, sorry

hi！are you solve this problem？i have the same problem.
