### ISSUE TITLE
Training failed about monocap dataset

### ISSUE THREAD

**Issue by Mr-ind1fferent** [skhu101/GauHuman#28]
Thanks for the amazing work!

There is some bugs that i can not train on monocap.

![image](https://github.com/skhu101/GauHuman/assets/74087260/fd4da752-5456-4ba2-955e-2ba850483f55)
![image](https://github.com/skhu101/GauHuman/assets/74087260/c7cd13ac-9719-4018-9b7e-d33cfb8f5e30)
![image](https://github.com/skhu101/GauHuman/assets/74087260/9e57b531-b5b5-45fa-887a-4145545246c0)

But it is ok when i use vlad_images1011,

![image](https://github.com/skhu101/GauHuman/assets/74087260/3798ec9c-526b-4dcb-b773-64893146ce67)

I am so confused.

**Comment by skhu101** [comment]
It is quite strange. Do you successfully download the full data set?

**Comment by Mr-ind1fferent** [comment]
> It is quite strange. Do you successfully download the full data set?

Yes, i emailed yeaterday to get the download link and the dataset author told me the datasets are already preprocessed. So i did not do anything to the dataset.

**Comment by skhu101** [comment]
Hi, have you checked the mask directory? Maybe some files are missing when you download the data.
