### ISSUE TITLE
ZJUMoCapRefine Dataset

### ISSUE THREAD

**Issue by RockyXu66** [skhu101/GauHuman#3]
Hi,

I download the 'my_377' of ZJU-MoCap dataset from [instant-nvr](https://github.com/zju3dv/instant-nvr/blob/master/docs/install.md#set-up-datasets). But the folder only contains `annots_new.npy` instead of `annots.npy` in your [code](https://github.com/skhu101/GauHuman/blob/781539f9c8b92a0b868521bcbb021ae88e62814c/scene/dataset_readers.py#L561).

If I change the file name in the code and load `annots_new.npy`, [annots](https://github.com/skhu101/GauHuman/blob/781539f9c8b92a0b868521bcbb021ae88e62814c/scene/dataset_readers.py#L562) only contains '**cams**' while '**ims**' is empty.

**Comment by skhu101** [comment]
Hi, thanks for your interest in our work. We have checked the ZJU-MoCap-Refine data set and found that annots.npy is contained in the original data set. We have also verified this with the authors of instant-nvr. Maybe you can redownload the dataset and hope this can solve your problem.

**Comment by RockyXu66** [comment]
> Hi, thanks for your interest in our work. We have checked the ZJU-MoCap-Refine data set and found that annots.npy is contained in the original data set. We have also verified this with the authors of instant-nvr. Maybe you can redownload the dataset and hope this can solve your problem.

Thanks for your reply. 
But sorry, I am still a little confused. Are you saying that I should copy the `annots.npy` file from the original data set and place it into the ZJU-MoCap-Refine data set? The `annots.npy` file in the original data set contains 'ims' values, but the image paths inside are in the style of 'Camera_B1/000000.jpg'. Should I replace the folder path from 'Camera_B1' to 'images/00', which corresponds to the ZJU-MoCap-Refine data set?

**Comment by skhu101** [comment]
Hi, the annots.npy file is contained in the ZJU-MoCap-Refine data set. You can redownload the ZJU-MoCap-Refine data set for a further check.

**Comment by gcgeng** [comment]
Hi, the maintainer of zju-mocap data here. I think there might be some discrepancies in packing the data. Could you please try to download the `annots` files from [here](https://office365stanford-my.sharepoint.com/:u:/g/personal/gengchen_stanford_edu/EdZYvYTYMmJPi6-DT0VQYj0BzG_6aZCCh8OJ-scgu2uKRA?e=k1AQ3l) and let me know whether it works? Thanks.

**Comment by theAdityaRamesh** [comment]
Hi @gcgeng can you check the COLMAP image files for subj 377. They are not correct.

**Comment by gcgeng** [comment]
> Hi @gcgeng can you check the COLMAP image files for subj 377. They are not correct.

Could you please provide more specific details about your query? I would like to know which particular file you are referring to, and what issues you are encountering with it.

**Comment by Dragon2938734** [comment]
excuse me,  i follow the link from [instant-nvr](https://github.com/zju3dv/instant-nvr/blob/master/docs/install.md#set-up-datasets) and fill the form to download the dataset, but its name is just  ZJU-MoCap , and it subfolder are also not same name as the code. and can i just change the folder name to settle it?
<img width="452" alt="image" src="https://github.com/skhu101/GauHuman/assets/119784366/7bcdb695-9978-4f27-ac32-9d2d52118061">
<img width="947" alt="image" src="https://github.com/skhu101/GauHuman/assets/119784366/fadb547c-9e09-4419-8f20-e1be09f4ca35">
<img width="659" alt="image" src="https://github.com/skhu101/GauHuman/assets/119784366/3065d05f-4cea-4519-a2f4-36d6c28d2dc5">

**Comment by skhu101** [comment]
Yes, you can.
