### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by haloann666** [skhu101/GauHuman#30]
Can you tell me the command line in train_zju_mocap_refine.sh has -eval and eval_zju_mocap_refine.sh does not have the -eval grin?
I see the code without -eval, test_cam_infos = [] would be equal to null. Wouldn't there be no new perspective rendering.

**Comment by haloann666** [comment]
render.py
 if not skip_test:
             render_set(dataset.model_path, "test", scene.loaded_iter, scene.getTestCameras(), gaussians, pipeline, background)
  
  scene.getTestCameras() will be null

**Comment by skhu101** [comment]
Thanks for your message. -eval means you will evaluate the model performance on test sets in the training stage.
