### ISSUE TITLE
Request for Training Code Used for InstantAvatar

### ISSUE THREAD

**Issue by wheltz** [skhu101/GauHuman#31]
I was inspired by your work in the GauHuman paper where you retrained InstantAvatar on the ZJU-Mocap and MonoCap datasets. I am interested in replicating the results presented.
Could you please share the code used for this specific retraining? It would greatly assist in my research.

**Comment by skhu101** [comment]
Below is the link for our retrained InstantAvatar code on the ZJU-Mocap and MonoCap datasets. You can follow one command example in readme.txt for training and evaluation purposes. 
https://drive.google.com/file/d/1ySpU5GyGUrHmxWUZHiMST2URecxC5aIx/view
