### ISSUE TITLE
dataset about People_SnapShot

### ISSUE THREAD

**Issue by JiatengLiu** [skhu101/GauHuman#32]
Hello!!
Have you test your framework on dataset People_SnapShot?

**Comment by skhu101** [comment]
No, we did not test it on People_SnapShot data set.

**Comment by JiatengLiu** [comment]
Thanks for your reply, and I want to test it on people_snapshot, do you know how to process data sets to fit GauHuman?

**Comment by skhu101** [comment]
Hi, maybe one quick way is to follow the data loader used in GauHuman.

**Comment by JiatengLiu** [comment]
Thanks for your reply, I have tried like this but some parameters were wrong. such as theta in smpl params is not zero in people_snapshot, which is zero in zju_mocap. I tried to assign them directly to zero and got what plausible result like below. But you know, deleting data from a data set is not an appropriate thing to do.
![image](https://github.com/skhu101/GauHuman/assets/77832807/985ef68d-e11e-40c1-8aad-db2e013f7702)

**Comment by skhu101** [comment]
Hi, I would suggest you check by projecting SMPL vertices to the image space. Try to make sure that SMPL parameters are correctly loaded.

**Comment by JiatengLiu** [comment]
Thanks for your suggest! I have fix it:&gt;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, May 16, 2024 09:34 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [skhu101/GauHuman] dataset about People_SnapShot (Issue #32)

&nbsp;



 
Hi, I would suggest you check by projecting SMPL vertices to the image space. Try to make sure that SMPL parameters are correctly loaded.

**Comment by yashgarg98** [comment]
Hi @skhu101 and @JiatengLiu, can you let me know how you created/preprocessed the files to create the dataloader for the people_snapshot dataset? I have followed the https://github.com/zju3dv/instant-nvr/blob/master/docs/preprocess.md to create the files but I'm assuming some files are still missing.

Thanks

**Comment by JiatengLiu** [comment]
Hi @yashgarg98, Just follow this repo, processing datasets in this repo is suitable for GauHuman's needs.
https://github.com/wenbin-lin/RelightableAvatar

**Comment by Yi-Cheng0101** [comment]
Hi @JiatengLiu, I follow the repo you provided. But, they still missed some files, such as annots.npy and smpl_params. Could you share how you get them through the repo you shared. Thanks!

**Comment by JiatengLiu** [comment]
My directory looks like this, using male-3-casual as an example.
```
├── camera.pkl
├── consensus.obj
├── consensus.pkl
├── image
├── keypoints.hdf5
├── lbs
├── male-3-casual.mp4
├── mask
├── masks.hdf5
├── params.npy
├── reconstructed_poses.hdf5
├── tex-male-3-casual.jpg
└── vertices
```
If you need, I can share my dataset with you:> @Yi-Cheng0101

**Comment by Yi-Cheng0101** [comment]
Hi @JiatengLiu , Thank you for the reply. I have the same format as your dataset. But this format doesn't like zju_mocap. How do you load these data into training steps? Thanks!

**Comment by XingFen-Xie** [comment]
Hi @JiatengLiu , I have the same dataset format and  write peoplesnapshot's data loader with reference to readCamerasZJUMoCapRefine, but I have the problem in the picture
![img](https://github.com/user-attachments/assets/a39b9636-2606-4613-9cad-0714b813599f)
 can you share your dataloader? Thanks!

**Comment by JiatengLiu** [comment]
Could you provide more info like the GT  image? @XingFen-Xie
 I remember that if you code the dataloader in the format of the zju dataset you might get an upside down person, probably because of a different coordinate system. I could provide my script for reading snapshot dataset and how can I contact you? @XingFen-Xie @Yi-Cheng0101

**Comment by XingFen-Xie** [comment]
hi @JiatengLiu, I can not find the gt, but the people should be in the middle of the picture, not in the bottom. Could you please share your code with me via email? Thank you very much!  My email address is 2983150767@qq.com. Thank you very much!

**Comment by ivyyy77** [comment]
@JiatengLiu Hi, could you pls kindly help to share your script for reading people_snapshot dataset with me? I would really appreciate it. My email address is hzs0615@163.com. Many thanks for your help.

**Comment by CODINGHYE** [comment]
@JiatengLiu Hi, thank you for sharing the process to train people_snapshot! The context you provided was incredibly helpful. By any chance, would you be able to share your script for reading people_snapshot? I would greatly appreciate it. My email address is didgpfl20@gmail.com. Thank you so much for your help!

**Comment by hengyu-wang** [comment]
> Could you provide more info like the GT image? [@XingFen-Xie](https://github.com/XingFen-Xie) I remember that if you code the dataloader in the format of the zju dataset you might get an upside down person, probably because of a different coordinate system. I could provide my script for reading snapshot dataset and how can I contact you? [@XingFen-Xie](https://github.com/XingFen-Xie) [@Yi-Cheng0101](https://github.com/Yi-Cheng0101)

Hi, can you also share with me a script for processing people_snapshot? My email address is why3065610930@163.com. Thank you very much for your help!

**Comment by HandSomeWay** [comment]
Hi @JiatengLiu , could you also share with me the script for processing people_snapshot? My email address is 1278863264@qq.com. Thank you very much for your help!

**Comment by JiatengLiu** [comment]
Sorry for occupying public resources and wasting everyone's time, because I haven't done research related to human avatar for a long time. I found this script in my storage, it seems feasible, just for your reference.[link](https://drive.google.com/file/d/14atbnzdOvbWYMT6uuNumPRZDhAF9dyq0/view?usp=drive_link)

**Comment by HandSomeWay** [comment]
> Sorry for occupying public resources and wasting everyone's time, because I haven't done research related to human avatar for a long time. I found this script in my storage, it seems feasible, just for your reference.[link](https://drive.google.com/file/d/14atbnzdOvbWYMT6uuNumPRZDhAF9dyq0/view?usp=drive_link)

thank you for sharing！ i will explore it

**Comment by radiant123456789** [comment]
> My directory looks like this, using male-3-casual as an example.我的目录看起来是这样的，以 male-3-casual 为例。
> 
> ```
> ├── camera.pkl
> ├── consensus.obj
> ├── consensus.pkl
> ├── image
> ├── keypoints.hdf5
> ├── lbs
> ├── male-3-casual.mp4
> ├── mask
> ├── masks.hdf5
> ├── params.npy
> ├── reconstructed_poses.hdf5
> ├── tex-male-3-casual.jpg
> └── vertices
> ```
> 
> If you need, I can share my dataset with you:> 如果你需要，我可以和你分享我的数据集：>[@Yi-Cheng0101](https://github.com/Yi-Cheng0101)

你好，我该如何获得这些文件呢
