### ISSUE TITLE
about mask loss

### ISSUE THREAD

**Issue by yangqinhui0423** [skhu101/GauHuman#34]
Dear authors! Thanks for your excellent work.
I have a question about the mask loss. I am confused about the code.  Is the bkgd_mask and alpha mask used to compute the mask loss? Where is the ground truth mask? And the bound_mask=1 means the person region or others?
By the way, when inference, do we neek the mask as input?

**Comment by skhu101** [comment]
Hi, bound_mask means the projected bounding box mask. bkgd_mask masks the human subject region.
