### ISSUE TITLE
Generalization Performance about  KL split/clone

### ISSUE THREAD

**Issue by BruceLz** [skhu101/GauHuman#35]
Great work. 
Have you ever tested KL split/clone performance in MVS scenarios, like static scenes with multi-camera?
When I try it, I see that the number of 3dgs has increased, not decreased, and the running time has not changed significantly. Is there something wrong?

**Comment by skhu101** [comment]
Hi, I did not try it in MVS scenarios. But it should work in such scenarios. I suggest that you try again by changing hyper-parameters.

**Comment by BruceLz** [comment]
Got it. Thanks.
