### ISSUE TITLE
Is GauHuman using unmodified GSplat Rasterizer?

### ISSUE THREAD

**Issue by Rajrup** [skhu101/GauHuman#36]
Thanks a lot for sharing this fantastic work!

**Question:** I see that you have added the `diff-gaussian-rasterization` as a submodule (https://github.com/skhu101/GauHuman/tree/main/submodules/diff-gaussian-rasterization) with the repo and not as a git submodule. I wonder if GauHuman uses a modified Gsplat rasterizer developed on top of the original repo https://github.com/graphdeco-inria/diff-gaussian-rasterization.

**Comment by skhu101** [comment]
Hi, we implement the [alpha mask loss version](https://github.com/ashawkey/diff-gaussian-rasterization) based on the official [diff-gaussian-rasterization](https://github.com/graphdeco-inria/diff-gaussian-rasterization/tree/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d).
