### ISSUE TITLE
Adaption to SMPLX 

### ISSUE THREAD

**Issue by SeanChenxy** [skhu101/GauHuman#37]
Hi, Thanks for sharing the codes. Is there any way to use SMPLX (instead of SMPL) for human driving?

**Comment by skhu101** [comment]
Yes, our code is compatible with SMPLX for human animation.

**Comment by SeanChenxy** [comment]
So, how should I modify `train_zju_mocap_refine.sh` to adopt SMPLX?

**Comment by skhu101** [comment]
Hi, our code is compatible with SMPLX. All you need is to fit SMPLX models for the refined zju_mocap dataset.

**Comment by DarcyFan** [comment]
> So, how should I modify `train_zju_mocap_refine.sh` to adopt SMPLX?

Hi，Have you finished to use the SMPLX instead of SMPL for human driving?
If  yes, could you tell me how to use SMPLX in Gauhuman?
Thank you!
