### ISSUE TITLE
Some question about ZJUMOCAP-refine dataset

### ISSUE THREAD

**Issue by Fiiiiifi** [skhu101/GauHuman#38]
Hello！ Your work is remarkable! I would like to ask if there are any differences in the camera parameters between the refined ZJUMocap dataset and the original ZJUMocap dataset. If I want to directly use the ZJUMocap dataset in the original Gaussian splatting generation work, which dataset should I use?

**Comment by skhu101** [comment]
Hi, we use a refined ZJUMocap dataset. The authors refine the camera and SMPL parameters of the original ZJUMocap dataset. Some details can be found in https://github.com/zju3dv/mlp_maps/blob/master/INSTALL.md.
