### ISSUE TITLE
Failed to build wheel for pickle5

### ISSUE THREAD

**Issue by yangqinhui0423** [skhu101/GauHuman#4]
Hello, thanks for your excellent work!
I met a problem when "pip install -r requirement.txt". I was stuck on installing pickle5. I also tried _conda install -c conda-forge pickle5_ but it doesn't work. I wnat to know if anyone else meet the same problem. 

**The error information is as follows：**
Building wheels for collected packages: pickle5
  Building wheel for pickle5 (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\pickle5
      copying pickle5\pickle.py -> build\lib.win-amd64-cpython-38\pickle5
      copying pickle5\pickletools.py -> build\lib.win-amd64-cpython-38\pickle5
      copying pickle5\__init__.py -> build\lib.win-amd64-cpython-38\pickle5
      creating build\lib.win-amd64-cpython-38\pickle5\test
      copying pickle5\test\pickletester.py -> build\lib.win-amd64-cpython-38\pickle5\test
      copying pickle5\test\test_pickle.py -> build\lib.win-amd64-cpython-38\pickle5\test
      copying pickle5\test\test_picklebuffer.py -> build\lib.win-amd64-cpython-38\pickle5\test
      copying pickle5\test\__init__.py -> build\lib.win-amd64-cpython-38\pickle5\test
      running build_ext
      building 'pickle5._pickle' extension
      creating build\temp.win-amd64-cpython-38
      creating build\temp.win-amd64-cpython-38\Release
      creating build\temp.win-amd64-cpython-38\Release\pickle5
      "D:\Visual studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\anaconda3\envs\gauhuman\include -ID:\anaconda3\envs\gauhuman\Include "-ID:\Visual studio\2022\Community\VC\Tools\MSVC\14.38.33130\include" "-ID:\Visual studio\2022\Community\VC\Tools\MSVC\14.38.33130\ATLMFC\include" "-ID:\Visual studio\2022\Community\VC\Auxiliary\VS\include" "-ID:\Windows Kits\10\include\10.0.22621.0\ucrt" "-ID:\Windows Kits\10\\include\10.0.22621.0\\um" "-ID:\Windows Kits\10\\include\10.0.22621.0\\shared" "-ID:\Windows Kits\10\\include\10.0.22621.0\\winrt" "-ID:\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcpickle5/_pickle.c /Fobuild\temp.win-amd64-cpython-38\Release\pickle5/_pickle.obj
      _pickle.c
      "D:\Visual studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\anaconda3\envs\gauhuman\include -ID:\anaconda3\envs\gauhuman\Include "-ID:\Visual studio\2022\Community\VC\Tools\MSVC\14.38.33130\include" "-ID:\Visual studio\2022\Community\VC\Tools\MSVC\14.38.33130\ATLMFC\include" "-ID:\Visual studio\2022\Community\VC\Auxiliary\VS\include" "-ID:\Windows Kits\10\include\10.0.22621.0\ucrt" "-ID:\Windows Kits\10\\include\10.0.22621.0\\um" "-ID:\Windows Kits\10\\include\10.0.22621.0\\shared" "-ID:\Windows Kits\10\\include\10.0.22621.0\\winrt" "-ID:\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcpickle5/picklebufobject.c /Fobuild\temp.win-amd64-cpython-38\Release\pickle5/picklebufobject.obj
      picklebufobject.c
      pickle5/picklebufobject.c(19): warning C4273: “PyPickleBuffer_FromObject”: dll 链接不一致
      D:\anaconda3\envs\gauhuman\include\picklebufobject.h(18): note: 参见“PyPickleBuffer_FromObject”的前一个定义
      pickle5/picklebufobject.c(38): warning C4273: “PyPickleBuffer_GetBuffer”: dll 链接不一致
      D:\anaconda3\envs\gauhuman\include\picklebufobject.h(22): note: 参见“PyPickleBuffer_GetBuffer”的前一个定义
      pickle5/picklebufobject.c(57): warning C4273: “PyPickleBuffer_Release”: dll 链接不一致
      D:\anaconda3\envs\gauhuman\include\picklebufobject.h(24): note: 参见“PyPickleBuffer_Release”的前一个定义
      pickle5/picklebufobject.c(208): warning C4273: “PyPickleBuffer_Type”: dll 链接不一致
      D:\anaconda3\envs\gauhuman\include\picklebufobject.h(13): note: 参见“PyPickleBuffer_Type”的前一个定义
      "D:\Visual studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\anaconda3\envs\gauhuman\libs /LIBPATH:D:\anaconda3\envs\gauhuman /LIBPATH:D:\anaconda3\envs\gauhuman\PCbuild\amd64 "/LIBPATH:D:\Visual studio\2022\Community\VC\Tools\MSVC\14.38.33130\ATLMFC\lib\x64" "/LIBPATH:D:\Visual studio\2022\Community\VC\Tools\MSVC\14.38.33130\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:D:\Windows Kits\10\\lib\10.0.22621.0\\um\x64" /EXPORT:PyInit__pickle build\temp.win-amd64-cpython-38\Release\pickle5/_pickle.obj build\temp.win-amd64-cpython-38\Release\pickle5/picklebufobject.obj /OUT:build\lib.win-amd64-cpython-38\pickle5\_pickle.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-38\Release\pickle5\_pickle.cp38-win_amd64.lib
        正在创建库 build\temp.win-amd64-cpython-38\Release\pickle5\_pickle.cp38-win_amd64.lib 和对象 build\temp.win-amd64-cpython-38\Release\pickle5\_pickle.cp38-win_amd64.exp
      正在生成代码
      已完成代码的生成
      picklebufobject.obj : error LNK2005: PyPickleBuffer_GetBuffer 已经在 python38.lib(python38.dll) 中定义
      build\lib.win-amd64-cpython-38\pickle5\_pickle.cp38-win_amd64.pyd : fatal error LNK1169: 找到一个或多个多重定义的符号
      error: command 'D:\\Visual studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\link.exe' failed with exit code 1169
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pickle5
  Running setup.py clean for pickle5
Failed to build pickle5
ERROR: Could not build wheels for pickle5, which is required to install pyproject.toml-based projects

**Comment by yangqinhui0423** [comment]
When I tried Python3.9，I met error as follows：
_Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pickle5 -> python[version='3.6.*|3.7.*']
  - pickle5 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that._

Maybe the version of python should be 3.7?

**Comment by theAdityaRamesh** [comment]
I got the same error I re-ran the setup after deleting the conda env with the same code in README it ran.

**Comment by skhu101** [comment]
Hi, I did not encounter this problem when preparing the conda environment. Do you follow the same command to prepare the conda environment?

**Comment by 2213826090** [comment]
I met same problem on python 3.10. then I replaced the "import pickle5 .." with "import pickle" in mmhuman3d, and remove the pickle5 in requirement of mmhumand 3d, then manually install it.

**Comment by TonyDua** [comment]
> I met same problem on python 3.10. then I replaced the "import pickle5 .." with "import pickle" in mmhuman3d, and remove the pickle5 in requirement of mmhumand 3d, then manually install it.

well done. it is work for me !!!(python 3.9)
