### ISSUE TITLE
transform of normal

### ISSUE THREAD

**Issue by JiatengLiu** [skhu101/GauHuman#40]
Hi, I have some questions about how to transform normal map.  I used a prediction network to get two normal maps of front and back, which should be opposite. I don't know how to correctly convert these normal lines under different poses to the world coordinate system, can you tell me?
![image](https://github.com/user-attachments/assets/03c257fe-051e-4902-b2d4-9351cd5283ea)
![image](https://github.com/user-attachments/assets/5bf05a75-4e98-4c74-9175-3381946a5dad)

**Comment by skhu101** [comment]
I also do not have a particular idea. I have tried to get the normal image through gradients of sampled points in neural radiance fields. But it is a different setting.

**Comment by JiatengLiu** [comment]
Yes, I can only do this task in an approximate way, because ellipsoidal 3D Gaussians is not very friendly for geometry properties like normal.
