### ISSUE TITLE
How to get the rotation matrix representing the orientation of the human body？

### ISSUE THREAD

**Issue by JiatengLiu** [skhu101/GauHuman#41]
As mentioned in the title.

**Comment by skhu101** [comment]
Hi, do you mean lookat camera matrix? If so, you can refer to https://github.com/skhu101/GauHuman/issues/29.

**Comment by JiatengLiu** [comment]
Thanks for your reply! I have know how to solve it.

**Comment by JiatengLiu** [comment]
I checked #29, which does not solve my problem, but I found what I need, the orientation of the human body corresponds to `smpl_param['R']`, just apply it to the normal, sorry to bother you.
