### ISSUE TITLE
How to change the number of 3d Gauss initializations

### ISSUE THREAD

**Issue by DarcyFan** [skhu101/GauHuman#42]
Hi, Amazing Job! But I'm a little confused that as you mentioned in your paper, you changed the number of 3D Gauss initializations to test the effect, but how do I change the number of 3D Gauss Initializations in this code?

**Comment by skhu101** [comment]
Hi, thanks for your interest in our work. You can specify the number of 3D Gaussians for the refined ZJU_MoCap dataset at https://github.com/skhu101/GauHuman/blob/732ec0d6783a29743f607cc0dce34ac08f57d0b0/scene/dataset_readers.py#L726.

**Comment by DarcyFan** [comment]
> Hi, thanks for your interest in our work. You can specify the number of 3D Gaussians for the refined ZJU_MoCap dataset at
> 
> https://github.com/skhu101/GauHuman/blob/732ec0d6783a29743f607cc0dce34ac08f57d0b0/scene/dataset_readers.py#L726
> 
> .

Thanks for your reply.But when I change the num_pts, an error is reported because SMPL initializes with only 6890 points in the canonical space,which means the paras 'xyz' only contains 6890 points.

**Comment by skhu101** [comment]
Hi, when you change the number of num_pts, you also need to reset the number of paras 'xyz'. In our case, we randomly set the paras 'xyz' for an ablation study.

**Comment by DarcyFan** [comment]
> Hi, when you change the number of num_pts, you also need to reset the number of paras 'xyz'. In our case, we randomly set the paras 'xyz' for an ablation study.

Thanks for your reply. Could you show your code for initialize 'xyz'? Because in your code, you're initializing 'xyz' with 6890 points of SMPL's BigPose.

**Comment by skhu101** [comment]
You can use the following line to achieve what you want. 
xyz = np.random.random((num_pts, 3)) * (train_cam_infos[0].big_pose_world_bound[1] - train_cam_infos[0].big_pose_world_bound[0])  + train_cam_infos[0].big_pose_world_bound[0]
