### ISSUE TITLE
training process 

### ISSUE THREAD

**Issue by Yi-Cheng0101** [skhu101/GauHuman#43]
Hi,
I have a question regarding the `bigpose_uvh.npy` file. From what I understand, this file contains the color data used for `UV mapping in the SMPL point cloud`. Could you please explain how or where the 2D images are processed to generate the bigpose_uvh.npy file? I want to make sure I understand this correctly.

Thank you for your time and assistance!

**Comment by skhu101** [comment]
Hi, thanks for your interest. Could you remind me where we use the bigpose_uvh.npy file?

**Comment by Yi-Cheng0101** [comment]
Hi, I thought I misunderstood the training process. There is no problem with this issue. But I still have the other question about "smpl_rot.pickle." What is the relationship between these files and SMPL? I know that this file contains transform and translation data of each camera view but I didn't know the relationship with SMPL. Thanks!

**Comment by skhu101** [comment]
Hi, this file contains the pose vector of SMPL. You can refer to https://github.dev/skhu101/GauHuman/blob/732ec0d6783a29743f607cc0dce34ac08f57d0b0/gaussian_renderer/__init__.py#L59 for more details.
