### ISSUE TITLE
Questions about code modifications for the pre-calculation of covariance

### ISSUE THREAD

**Issue by MyNiuuu** [skhu101/GauHuman#44]
Hi!

Thanks for the wonderful work!

I find some unique modifications of the function `build_covariance_from_scaling_rotation` in your implementation (https://github.com/skhu101/GauHuman/blob/main/scene/gaussian_model.py#L32):

```
def build_covariance_from_scaling_rotation(scaling, scaling_modifier, rotation, transform):
    L = build_scaling_rotation(scaling_modifier * scaling, rotation)
    actual_covariance = L @ L.transpose(1, 2)
    if transform is not None:
        actual_covariance = transform @ actual_covariance
        actual_covariance = actual_covariance @ transform.transpose(1, 2)
    symm = strip_symmetric(actual_covariance)
    return symm
```

The original implementation of 3DGS are as follows (https://github.com/graphdeco-inria/gaussian-splatting/blob/main/scene/gaussian_model.py#L27):
```
def build_covariance_from_scaling_rotation(scaling, scaling_modifier, rotation):
    L = build_scaling_rotation(scaling_modifier * scaling, rotation)
    actual_covariance = L @ L.transpose(1, 2)
    symm = strip_symmetric(actual_covariance)
    return symm
```

May I ask what is the reason of this addition of the 3x3 transform matrix for calculating the covariance? Is it because of the projection from the canonical space to the observation space?

Thanks a lot!

**Comment by skhu101** [comment]
Yes, you are right.

**Comment by MyNiuuu** [comment]
Thanks！
