### ISSUE TITLE
 dataset about DNA-Rendering

### ISSUE THREAD

**Issue by Yi-Cheng0101** [skhu101/GauHuman#46]
Hi,
Have you test your framework on dataset DNA-Rendering? Thanks!

**Comment by skhu101** [comment]
Hi, thanks for your interest in our work. We test the performance on two sequences (0012_09 and 0025_11 from part 1 of DNA-Rendering).

**Comment by Yi-Cheng0101** [comment]
Thanks! Could you share the command you execute the DNA-Rendering  in training and evaluation. Thanks!

**Comment by skhu101** [comment]
Hi, below is the command for training and evaluation. 

python train.py -s data/dna_rendering/part_1/main/0012_09.smc --eval --exp_name dna_rendering/0012_09_100_pose_correction_lbs_offset --motion_offset_flag --iterations 3000

python render.py -m output/dna_rendering/0012_09_100_pose_correction_lbs_offset --motion_offset_flag --iteration 3000

**Comment by qianqiuzzz** [comment]
About the experiment results on dna_rendering,  the gt images is raw formats with background , masked, or croped?
I would like to know the details of your processing of dna-rendering
