### ISSUE TITLE
code about visualization results in Fig. 3 of main paper.

### ISSUE THREAD

**Issue by yjh576** [skhu101/GauHuman#48]
I have been exploring your GitHub repository and found it extremely helpful for understanding your work. However, I couldn't locate the code related to the visualization presented in Figure 3 of your paper.

Could you please let me know if this part of the code is available? If possible, could you consider open-sourcing it or sharing it with me?

Thank you for your assistance and for your valuable contributions to the field.

**Comment by skhu101** [comment]
Hi, thanks for your interest in our work. You can use our evaluation code to get the evaluation results.

**Comment by yjh576** [comment]
I'm able to obtain the final numerical results (e.g., PSNR, etc.), but I couldn't find the rendered images in the evaluation output. Or should I rewrite this part of the code to obtain the rendered image visualizations?

**Comment by skhu101** [comment]
Hi, you should get rendered image visualization results by running our evaluation code. You can refer to         torchvision.utils.save_image(rendering, os.path.join(render_path, '{0:05d}'.format(id) + ".png")) in render.py.
