### ISSUE TITLE
How to render people in canonical/T pose

### ISSUE THREAD

**Issue by JiatengLiu** [skhu101/GauHuman#49]
Hi, Shoukang.
I want to know how to render the people in the T-pose. 
I have tried to skip the process `coarse_deform_c2source`, but the rendering results is all zeros, how can I fix it?

**Comment by JiatengLiu** [comment]
I commented on the code below, but the result was not a face facing the camera like below.
```
can_pts = torch.matmul(A_fif[..., :3, :3], query_pts[..., None]).squeeze(-1)
smpl_src_pts = can_pts + A_fif[..., :3, 3]
```
![image](https://github.com/user-attachments/assets/504c6cbe-1d24-4ba3-819b-151512454f7b)

**Comment by skhu101** [comment]
Hi, thanks for your interest. Do you visualize rendered images in T-pose?

**Comment by JiatengLiu** [comment]
yes, besides I want to render people towards cameras with T-pose.

**Comment by skhu101** [comment]
Hi, you can set the target pose to be T-pose to have a debug. You can get rendered results under T-pose by skipping the coarse_deform_c2source function.

**Comment by JiatengLiu** [comment]
Hi, Shoukang, I have followed your guide to skip the `coarse_deform_c2source` function, but the results is not what I wished. Results is like below.
![image](https://github.com/user-attachments/assets/c3e407ba-518b-4d64-b032-a697c3c45f93)
What I want to get is like below.
![image](https://github.com/user-attachments/assets/544098d5-0406-4f26-9a9d-767de892cd45)
Or can we turn the problem into how to remove the steering of the human body during rendering so that the human body is always facing the camera

**Comment by skhu101** [comment]
Hi, if you hope to use the same camera as the target image, you can change the target pose to be T-pose while keeping other parameters (shape, camera parameters) the same. The other solution is to set up a lookat camera by referring to https://github.com/skhu101/GauHuman/issues/29.

**Comment by JiatengLiu** [comment]
Thanks for your reply! I will try later.

Best!



At 2024-10-21 22:34:08, "Shoukang Hu" ***@***.***> wrote:

Hi, if you hope to use the same camera as the target image, you can change the target pose to be T-pose while keeping other parameters (shape, camera parameters) the same. The other solution is to set up a lookat camera by referring to #29.
