### ISSUE TITLE
About dataset.py

### ISSUE THREAD

**Issue by sHaol0w** [skhu101/GauHuman#5]
Hi, seems there should be zjumocap related data.py files in data folder?

**Comment by theAdityaRamesh** [comment]
You have to download it as per the instructions in README.md and then save it in data.py or modify the dataset variable in the eval and train .sh files

**Comment by skhu101** [comment]
Hi, thanks for your interest in our work. We use the refined version of zju_mocap data set provided by authors of InstantNVR. You can find the dataloader script in GauHuman/scene/dataset_readers.py.

**Comment by sHaol0w** [comment]
@skhu101
Thank you for your kind reply. I should recognize that, sorry o(╥﹏╥)o.
