### ISSUE TITLE
How to save the 3d Gaussian point cloud with the corresponding pose for each frame

### ISSUE THREAD

**Issue by DarcyFan** [skhu101/GauHuman#50]
Hello, I want to save the video stream with the color 3D Gauss Point Cloud, so I need to save the point cloud for each frame with corresponding pose, and do you know how can I implement this?
thanks!

**Comment by skhu101** [comment]
Hi, you can save the point cloud for each frame by referring to the transformation code defined in  https://github.dev/skhu101/GauHuman/blob/732ec0d6783a29743f607cc0dce34ac08f57d0b0/gaussian_renderer/__init__.py#L70-L71.
