### ISSUE TITLE
Initialization with a picture instead of a vedio

### ISSUE THREAD

**Issue by ccxi1008** [skhu101/GauHuman#51]
Thanks for your work! I'm trying to use one picture instead of a vedio to get the initialized 3D Gaussians in pose space with respect to SMPL and LBS model ，and still optimize the Guassians using the follow-up control process similar to the article. I'm wondering that:
1. if the 2 MLPs mentioned in the article are dedicated for each input data ? (Am I need to train dedicated MLPs for every input each time？）
2. What part of the code can I modify to change the input video to a single image？(Including what should I have for every item in my picture dataset)
3. Should my data need ground truth SMPL for every picture for initialization when training? Or I need SMPL for every item just for evaluation?
Thanks！

**Comment by skhu101** [comment]
Hi, thanks for your interest in our work. Do you hope to train a 3D Gaussian model with only one image? If this is the case, 1). you need to train 2 MLPs mentioned in the article. 2). You can refer to scene/dataset_readers.py to change the input from a video to a single image. 3). You need ground truth SMPL for training and testing data.
