### ISSUE TITLE
FileNotFoundError: No such file or directory: 'GauHuman/data/zju_mocap_refine/my_377/annots.npy'

### ISSUE THREAD

**Issue by sevennnn07** [skhu101/GauHuman#52]
hello，I followed the instructions of the README exactly, but while training, I got an error: FileNotFoundError: No such file or directory: 'GauHuman/data/zju_mocap_refine/my_377/annots.npy‘. Did I download the wrong dataset? If so, how can i download the right dataset?  Thanks!!

**Comment by skhu101** [comment]
Hi, thanks for your interest in our work. You can follow the instructions of [Instant-NVR](https://github.com/zju3dv/instant-nvr/blob/master/docs/install.md#set-up-datasets) to download ZJU-Mocap-Refine and MonoCap dataset.
