### ISSUE TITLE
some question about dataset

### ISSUE THREAD

**Issue by JiatengLiu** [skhu101/GauHuman#6]
Hi,What an amazing job! 
I have some questions. Do you have any plans to release the code for making the dataset? And more,for ZJU_mocap DATASETS?
And more, I observe the value of SEQUENCES in the bash : train_zju_mocap_refine is mismatched. Do I need to make some modifications?

**Comment by theAdityaRamesh** [comment]
Hey I managed to run train_zju_mocap_refine.sh as it is can you specify what you mean by mismatched sequence ?

**Comment by JiatengLiu** [comment]
@theAdityaRamesh   All I changed was the data dir, nothing else I changed. And then the program is running normally. Not sure if this answer solves your problem.
